import { type Camp } from "./camp";
import { mockCoordinator } from "./mock-data";

export const mockPastCamps: Camp[] = [
    {
        id: 901,
        name: 'Discover Pacific Taiwan Cycling Camp 2024',
        description: 'The 2024 version of our amazing Taiwan camp.',
        country: 'Taiwan',
        coordinator: mockCoordinator,
        date_start: '2024-07-12',
        date_end: '2024-07-26',
        age_min: 15,
        age_max: 18,
        price: 1100,
        status: 'CLOSED',
        entire_limit: 20,
        male_limit: 10,
        female_limit: 10,
        limit_per_country: 2,
    },
    {
        id: 902,
        name: 'Mandarian and culture exploring summer camp 2024',
        description: 'Learn Mandarin and explore Chinese culture.',
        country: 'China',
        coordinator: { ...mockCoordinator, id: 4, name: 'Li Wang' },
        date_start: '2024-06-15',
        date_end: '2024-07-01',
        age_min: 16,
        age_max: 19,
        price: 900,
        status: 'CLOSED',
        entire_limit: 25,
        male_limit: 10,
        female_limit: 15,
        limit_per_country: 2,
    },
    {
        id: 903,
        name: 'Explore Taiwan Cultural Culinary Camp 2024',
        description: 'A camp focused on the amazing food and culinary traditions of Taiwan.',
        country: 'Taiwan',
        coordinator: mockCoordinator,
        date_start: '2024-08-05',
        date_end: '2024-08-20',
        age_min: 17,
        age_max: 20,
        price: 1200,
        status: 'CANCELLED',
        entire_limit: 16,
        male_limit: 8,
        female_limit: 8,
        limit_per_country: 2,
    }
];
