package org.rotary.exchange.backend.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.rotary.exchange.backend.exception.ErrorResponse;
import org.rotary.exchange.backend.exception.ResourceNotFoundException;
import org.rotary.exchange.backend.model.Coordinator;
import org.rotary.exchange.backend.model.Country;
import org.rotary.exchange.backend.model.District;
import org.rotary.exchange.backend.repository.CoordinatorRepository;
import org.rotary.exchange.backend.repository.CountryRepository;
import org.rotary.exchange.backend.repository.DistrictRepository;
import org.rotary.exchange.backend.security.service.UserPrinciple;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/districts")
@RequiredArgsConstructor
@Tag(name = "Districts", description = "Rotary district operations")
public class DistrictController {

    private final DistrictRepository districtRepo;
    private final CoordinatorRepository coordinatorRepo;
    private final CountryRepository countryRepo;

    @Operation(
            summary = "Get all districts",
            description = "Retrieves all Rotary districts across all countries"
    )
    @ApiResponse(responseCode = "200", description = "Districts retrieved successfully")
    @GetMapping
    public List<District> getAllDistricts() {
        return districtRepo.findAll();
    }

    @Operation(
            summary = "Get district by ID",
            description = "Retrieves a specific Rotary district by its unique identifier"
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "District found"),
            @ApiResponse(responseCode = "404", description = "District not found",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    @GetMapping("/{id}")
    public District getDistrictById(
            @Parameter(description = "District ID", required = true, example = "1")
            @PathVariable Integer id) {
        return districtRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("District", "id", id));
    }

    @Operation(
            summary = "Create district",
            description = "Creates a new district within a country. Admin only.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "District created successfully"),
            @ApiResponse(responseCode = "400", description = "Validation error or duplicate district code"),
            @ApiResponse(responseCode = "401", description = "Not authenticated"),
            @ApiResponse(responseCode = "403", description = "Not authorized - requires ADMIN role"),
            @ApiResponse(responseCode = "404", description = "Country not found")
    })
    @PostMapping
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<District> createDistrict(@Valid @RequestBody DistrictRequest request) {
        Country country = countryRepo.findById(request.getCountryId())
                .orElseThrow(() -> new ResourceNotFoundException("Country", "id", request.getCountryId()));
        
        // Check for duplicate district code
        if (districtRepo.findByCode(request.getCode()).isPresent()) {
            throw new IllegalArgumentException("District with code '" + request.getCode() + "' already exists");
        }
        
        District district = new District();
        district.setCode(request.getCode());
        district.setCountry(country);
        // accessCode will be auto-generated by @PrePersist
        
        return ResponseEntity.ok(districtRepo.save(district));
    }

    @Operation(
            summary = "Update district",
            description = "Updates an existing district. Admin only.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "District updated successfully"),
            @ApiResponse(responseCode = "400", description = "Validation error or duplicate district code"),
            @ApiResponse(responseCode = "401", description = "Not authenticated"),
            @ApiResponse(responseCode = "403", description = "Not authorized - requires ADMIN role"),
            @ApiResponse(responseCode = "404", description = "District or country not found")
    })
    @PutMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<District> updateDistrict(
            @Parameter(description = "District ID", required = true, example = "1")
            @PathVariable Integer id,
            @Valid @RequestBody DistrictRequest request) {
        District district = districtRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("District", "id", id));
        
        Country country = countryRepo.findById(request.getCountryId())
                .orElseThrow(() -> new ResourceNotFoundException("Country", "id", request.getCountryId()));
        
        // Check for duplicate district code (excluding current district)
        districtRepo.findByCode(request.getCode())
                .filter(d -> !d.getId().equals(id))
                .ifPresent(d -> {
                    throw new IllegalArgumentException("District with code '" + request.getCode() + "' already exists");
                });
        
        district.setCode(request.getCode());
        district.setCountry(country);
        
        return ResponseEntity.ok(districtRepo.save(district));
    }

    @Operation(
            summary = "Delete district",
            description = "Deletes a district. Will fail if there are coordinators assigned to this district. Admin only.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "District deleted successfully"),
            @ApiResponse(responseCode = "401", description = "Not authenticated"),
            @ApiResponse(responseCode = "403", description = "Not authorized - requires ADMIN role"),
            @ApiResponse(responseCode = "404", description = "District not found"),
            @ApiResponse(responseCode = "409", description = "Cannot delete - district has assigned coordinators")
    })
    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<Void> deleteDistrict(
            @Parameter(description = "District ID", required = true, example = "1")
            @PathVariable Integer id) {
        District district = districtRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("District", "id", id));
        
        // Check if there are coordinators assigned to this district
        if (!coordinatorRepo.findByDistrictId(id).isEmpty()) {
            throw new IllegalStateException("Cannot delete district with assigned coordinators. Reassign coordinators first.");
        }
        
        districtRepo.delete(district);
        return ResponseEntity.noContent().build();
    }

    @Operation(
            summary = "Get district access code",
            description = "Retrieves the access code for a district. Admin only. Use this to generate student links.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Access code retrieved"),
            @ApiResponse(responseCode = "401", description = "Not authenticated"),
            @ApiResponse(responseCode = "403", description = "Not authorized - requires ADMIN role"),
            @ApiResponse(responseCode = "404", description = "District not found")
    })
    @GetMapping("/{id}/access-code")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<Map<String, String>> getAccessCode(
            @Parameter(description = "District ID", required = true, example = "1")
            @PathVariable Integer id) {
        District district = districtRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("District", "id", id));
        
        return ResponseEntity.ok(Map.of(
                "districtId", district.getId().toString(),
                "districtCode", district.getCode(),
                "accessCode", district.getAccessCode(),
                "studentLink", "/camps?code=" + district.getAccessCode()
        ));
    }

    @Operation(
            summary = "Regenerate district access code",
            description = "Generates a new access code for a district, invalidating the old one. Admin only.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "New access code generated"),
            @ApiResponse(responseCode = "401", description = "Not authenticated"),
            @ApiResponse(responseCode = "403", description = "Not authorized - requires ADMIN role"),
            @ApiResponse(responseCode = "404", description = "District not found")
    })
    @PostMapping("/{id}/regenerate-access-code")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<Map<String, String>> regenerateAccessCode(
            @Parameter(description = "District ID", required = true, example = "1")
            @PathVariable Integer id) {
        District district = districtRepo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("District", "id", id));
        
        // Force regeneration by setting to null and triggering @PrePersist
        district.setAccessCode(null);
        district.generateAccessCodeIfMissing();
        districtRepo.save(district);
        
        return ResponseEntity.ok(Map.of(
                "districtId", district.getId().toString(),
                "districtCode", district.getCode(),
                "accessCode", district.getAccessCode(),
                "studentLink", "/camps?code=" + district.getAccessCode()
        ));
    }

    // ===================== COORDINATOR ENDPOINTS =====================

    @Operation(
            summary = "Get my district's access code",
            description = """
                    Retrieves the access code for the coordinator's own assigned district.
                    
                    Coordinators can use this to generate and share student links for their district.
                    The link format is: /camps?code={accessCode}
                    """,
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Access code retrieved"),
            @ApiResponse(responseCode = "401", description = "Not authenticated"),
            @ApiResponse(responseCode = "404", description = "Coordinator has no assigned district")
    })
    @GetMapping("/my-access-code")
    public ResponseEntity<Map<String, String>> getMyAccessCode(
            @Parameter(hidden = true) Authentication authentication) {
        UserPrinciple userPrinciple = (UserPrinciple) authentication.getPrincipal();
        
        Coordinator coordinator = coordinatorRepo.findById(userPrinciple.getId())
                .orElseThrow(() -> new ResourceNotFoundException("Coordinator", "id", userPrinciple.getId()));
        
        if (coordinator.getDistrict() == null) {
            throw new ResourceNotFoundException("District", "coordinatorId", userPrinciple.getId());
        }
        
        District district = coordinator.getDistrict();
        return ResponseEntity.ok(Map.of(
                "districtId", district.getId().toString(),
                "districtCode", district.getCode(),
                "districtName", district.getCountry().getName() + " - " + district.getCode(),
                "accessCode", district.getAccessCode(),
                "studentLink", "/camps?code=" + district.getAccessCode()
        ));
    }

    // ===================== REQUEST DTOs =====================

    @Data
    @Schema(description = "District creation/update request")
    static class DistrictRequest {
        @NotBlank(message = "District code is required")
        @Schema(description = "Rotary district code", example = "1900", requiredMode = Schema.RequiredMode.REQUIRED)
        private String code;

        @NotNull(message = "Country ID is required")
        @Schema(description = "ID of the country this district belongs to", example = "1", requiredMode = Schema.RequiredMode.REQUIRED)
        private Integer countryId;
    }
}
